### ISSUE TITLE
Can't set menu attributes

### ISSUE THREAD

**Issue by nveid** [zerkalica/MillwrightMenuBundle#12]
I'm trying to set the menu attributes.. Basically by setting <ul> to have the class of <ul class="nav"> so it will work correctly with bootstrap...

perhaps you point me to where I'm doing something wrong here.

I tried.. 

```
millwright_menu:
   renderers:
      navigation: #menu type id
      attributes:
               class: "nav"
      renderer: null # custom renderer
      rendererOptions:
             template: SilvonaCoreAppBundle:Menu:front.html.twig
```

and I tried..

```
tree: #menu containers
    main: #main container
        type: navigation # menu type id
        attributes:
          class: "nav"
```

However, both ways I do it the <ul> from when the menu is generated still has no attributes attached to it.. Can you point me to what I'm doing wrong here?

Off topic, but on the same topic as well.. Do you know if there is setting to set to set a certain menu item "active" if the current route == the menu item?
