### ISSUE TITLE
Active menu item for multiple routes

### ISSUE THREAD

**Issue by nurikabe** [zerkalica/MillwrightMenuBundle#14]
Playing around the the bundle.  It's much easier to configure and maintain menus that with Knp alone.

I'm wondering if it's possible to mark a menu item as "current" for multiple routes.  For example, if  the user visits any of the following route names:

```
company
company_detailed
company_summary
```

And if I have a simple menu such as:

```
millwright_menu:
    tree: # menu containers
        main: # main container
            type: navigation # menu type id
            children:
                home: ~
                company: ~
                other: ~
```

Then I always want the company menu item to be highlighted "current" for the `company`, `company_detailed`, and `company_summary` routes.

Thanks!
